function(forge_add_fuzz_target target_name source_file)
  add_executable(${target_name} ${source_file})
  target_link_libraries(${target_name} PRIVATE forge_core)
  forge_apply_warnings(${target_name})
  forge_apply_sanitizers(${target_name})
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_definitions(${target_name} PRIVATE FORGE_USE_LIBFUZZER=1)
    target_compile_options(${target_name} PRIVATE -fsanitize=fuzzer-no-link)
    target_link_options(${target_name} PRIVATE -fsanitize=fuzzer)
  endif()
endfunction()
