function(forge_apply_sanitizers target_name)
  if(NOT FORGE_ENABLE_SANITIZERS OR MSVC)
    return()
  endif()
  if(NOT DEFINED FORGE_SANITIZER_SET)
    set(FORGE_SANITIZER_SET "address,undefined")
  endif()
  target_compile_options(${target_name} PRIVATE -fno-omit-frame-pointer -fsanitize=${FORGE_SANITIZER_SET})
  target_link_options(${target_name} PRIVATE -fsanitize=${FORGE_SANITIZER_SET})
endfunction()
